
version: "3"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql-server
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass
    volumes:
      - /root/mssql/data:/var/opt/mssql/data
      - /root/mssql/log:/var/opt/mssql/log
      - /root/mssql/secrets:/var/opt/mssql/secrets
